# Uses NodeJS V 11.13.0
image: node:11.13.0

# And to cache them as well.
cache:
  paths:
    - node_modules/
    - .yarn

# We tell GitLab to install all the packages
# before running anything.
# Docker images come with yarn preinstalled
before_script:
  - apt-get update -qq && apt-get install

# Specify the stages. Those are the steps that GitLab will go through
# Order matters.
stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  before_script:
    - yarn install
    - yarn global add lerna
  script:
    - yarn lint

Build:
  stage: build
  before_script:
    - yarn install
    - yarn global add lerna
  script:
    - lerna bootstrap
    - lerna run build

Test:
  stage: test
  when: manual
  before_script:
    - yarn install --frozen-lockfile
  script:
  # Installs Chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install google-chrome-stable -y
  # Runs the tests.
    - yarn test
