name: pages
on:
    push:
        branches:
            - master
jobs:
    clean-lint-build-test:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.20.2]

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: corepack enable
            - run: corepack install

            - name: install
              run: yarn install

            - name: lint
              run: yarn lint

            - name: build
              run: yarn build

            - name: pages
              working-directory: ./packages/facets-docs
              run: yarn pages

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: packages/facets-docs/pages
